name: Android Sign and Release

on:
  release:
    types: [published]

permissions:
  contents: write
  packages: write
  id-token: write

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Setup Android SDK
        uses: android-actions/setup-android@v2

      - name: Make gradlew executable
        run: chmod +x gradlew

      - name: Extract version from tag
        id: extract-version
        run: |
          VERSION=${GITHUB_REF#refs/tags/}
          VERSION=${VERSION#v}
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo "Extracted version: $VERSION"

      - name: Setup signing
        env:
          STORE_FILE: keystore.jks
          STORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
          KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
        run: |
          echo "${{ secrets.KEYSTORE_BASE64 }}" | base64 -d > $STORE_FILE
          chmod 600 $STORE_FILE
          echo "Keystore created at: $(realpath $STORE_FILE)"

      - name: Build signed APK
        env:
          STORE_FILE: keystore.jks
          STORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
          KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
        run: |
          ./gradlew assembleRelease

      - name: Find and upload APK
        run: |
          # 查找release APK（保留未签名检查以防构建失败）
          APK_PATH=$(find app/build/outputs/apk/ -name "app-release.apk" | head -n 1)
          
          if [ -z "$APK_PATH" ]; then
            echo "Available APKs:"
            find app/build/outputs/apk/ -name "*.apk" || echo "No APKs found"
            exit 1
          fi
          
          echo "Using APK at: $APK_PATH"
          echo "apk_path=$APK_PATH" >> $GITHUB_OUTPUT

      - name: Upload release asset
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ${{ env.APK_PATH || steps.find-apk.outputs.apk_path }}
          asset_name: sms-to-email-app-${{ steps.extract-version.outputs.version }}.apk
          asset_content_type: application/vnd.android.package-archive

      - name: Clean up
        if: always()
        run: |
          rm -f keystore.jks
          echo "Cleanup completed"